---
title: "MATH3012 problem sheet 3"
author: ""
date: ""
output: pdf_document
fontsize: 12pt
header-includes:
- \newcommand{\benum}{\begin{enumerate}}
- \newcommand{\eenum}{\end{enumerate}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\benum

\item Suppose $Y \sim \text{exponential}(\lambda)$, with p.d.f.
$f_Y(y; \lambda) = \lambda e^{- \lambda y}$, for $y > 0$ and $\lambda > 0$.
Show that the exponential distribution is a member
of the exponential family, and hence find $E(Y)$, $\text{Var}(Y)$, and
the variance function $V(\mu)$. 

\item Suppose $Y \sim \text{geometric}(p)$, with p.f.
$f_Y(y; p) = p(1 - p)^{y - 1}$, for $y \in \{1, 2, 3, \ldots\}$,
$p \in (0, 1)$. Show that the geometric distribution is a member
of the exponential family, and hence find $E(Y)$, $\text{Var}(Y)$, and
the variance function $V(\mu)$. 

\item What is the canonical link function for the exponential distribution (from Question 1)?
What about for the geometric distribution (from Question 2)?

\item Suppose that $Y_i$, $i=1, \ldots, n$ are independent $\text{Poisson}(\mu_i)$
random variables, that $x_i$ is an explanatory variable, and that
$$
\log \mu_i = \beta_1 + \beta_2 x_i.
$$
\benum
\item Write down the log-likelihood function of $\beta_1$ and
$\beta_2$ explicitly.  Hence,  derive a pair of simultaneous
equations, the solution of which are the maximum likelihood estimates for
$\bm \beta=(\beta_1, \beta_2)^T$.
\item Express the above model in terms of
$\bm \eta = X \bm \beta$
where $X$ is the appropriate  $n \times 2$ matrix.
\eenum

\eenum